### ISSUE TITLE
list of compatible/tested CPLDs and FPGAs

### ISSUE THREAD

**Issue by eadmaster** [sowbug/JTAGWhisperer#4]
Specifically i am interested to CPLDs manufactured by Atmel like the ATF15xx family.
If you have tried some of these please let me know if they are compatible.

**Comment by sowbug** [comment]
I made a wiki: https://github.com/sowbug/JTAGWhisperer/wiki

This was just a weekend project from a long time ago, and the XC9572XL is the only CPLD I've ever tinkered with, so I won't be adding anything to the list. But you're welcome to do so.
